### PR TITLE
Validation function for users data

### PR DESCRIPTION
**Pull request by ManyuDhyani**
This include validation for username, password, email, active, admin and verified fields of users data collection.

### CODE REVIEW

**Review by ralei0 — APPROVED** [review]
Good

**Comment by Kshitij-git24** [comment]
Done

**Review by chakravartikothadiya — APPROVED** [review]

**Review by Kshitij-git24 — COMMENTED** [review]
Done

**Review by Kshitij-git24 — APPROVED** [review]
Done

**Pull request merged**
